---
name: Maestro Mobile
version: 0.1.1
slug: maestro-mobile
description: "Use a Maestro UI testing framework
  within Home Assistant to automate interactions with
  your mobile device or emulator."
arch:
  - aarch64
  - amd64
url: "https://github.com/coder89/hassio-maestro-dev"
ingress: true
ingress_port: 7681
init: false
hassio_api: true
homeassistant_api: true
ports:
  5037/tcp: 5037
  9999/tcp: null
ports_description:
  5037/tcp: ADB server port
  9999/tcp: Maestro Studio web interface port - enable in Network tab if needed
host_network: true
usb: true
udev: true
map:
  - type: addon_config
    read_only: false
  - type: homeassistant_config
    read_only: false
services:
  - mqtt:need
options:
  adb_port: 5037
  auto_connect_devices: []
  auto_disable_triggers: false
schema:
  adb_port: port
  auto_connect_devices: [str]
  auto_disable_triggers: bool
  enable_studio: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/coder89/maestro-mobile/{arch}