---
name: Maestro
version: dev
slug: maestro
description: "Use a Maestro UI testing framework
  within Home Assistant to automate interactions with
  your mobile device or emulator."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/coder89/hassio-maestro-dev"
startup: services
ingress: true
ingress_port: 7681
init: false
webui: http://[HOST]:[PORT:9999]/
hassio_api: true
map:
  - addon_config:rw
  - homeassistant_config
ports:
  5037/tcp: 5037
  9999/tcp: 9999
ports_description:
  5037/tcp: ADB server port
  9999/tcp: Maestro Studio web interface port
host_network: true
usb: true
map:
  - type: addon_config
    read_only: False
    path: /custom
options:
  adb_port: 5037,
  auto_connect_devices: []
  flows: []
schema:
  adb_port: port
  auto_connect_devices: [str]
  flows:
    - name: str
      flow: str
  studio: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
