version: "3.8"

services:
  hass:
    build: ./maestro
    container_name: hass
    restart: unless-stopped
    privileged: true
    # depends_on:
    #   android:
    #     condition: service_healthy
    #volumes:
    #- ./bmw-conected-drive/flows:/flows  # Mount your Maestro YAML flows here
    #- ./apk:/apk  # Mount your APK files here
    #- /dev/bus/usb:/dev/bus/usb
    #ports:
    #  - "9998:9999"  # Expose Maestro Studio web interface
    #entrypoint: ["/run.sh"]
    command: ["tail", "-f", "/dev/null"] # Keeps container running for exec

networks:
  default:
    driver: bridge
